#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \

################## own scripts:	###########################
# extData related
alias mntExtData='sudo cryptsetup luksOpen /dev/disk/by-uuid/63b8095e-b0b1-423b-ac7d-ec13e77c7eae extData && sudo mount /dev/mapper/extData /mnt/extData'
alias umntExtData='sudo umount /mnt/extData && sudo cryptsetup luksClose /dev/mapper/extData'
alias backupHomedir='rsync -av --delete "$HOME" "/mnt/extData/Daten/SK-Homedir/" >> "$HOME/Documents/Zu_Sichern/Log_BackupHomeDir/HomeToExtData_LOG-`date +%Y-%m-%d-%X`" 2>&1'
alias backupExtDataToExtDataBackup1='rsync -av --delete  "/mnt/extData/Daten/" "/mnt/extDataBackup1/Daten" >> "$HOME/Documents/Zu_Sichern/Log_Backup_ExtData-to-ExtDataBackup1/Log_Backup_ExtData-to-ExtDataBackup1-`date +%Y-%m-%d-%X`" 2>&1'


alias mntExtDataBackup1='/home/maw/.local/bin/mountExtDataBackup1.sh'
alias umntExtDataBackup1='/home/maw/.local/bin/unmountExtDataBackup1.sh'

alias mntExtVid='/home/maw/.local/bin/mountExtVid.sh'
alias umntExtVid='/home/maw/.local/bin/unmountExtVid.sh'

alias mntExtMixedBackup1='/home/maw/.local/bin/mountExtMixedBackup1.sh'
alias umntExtMixedBackup1='/home/maw/.local/bin/unmountExtMixedBackup1.sh'

alias backupExtDataToMixedBackup1='rsync -av --delete  "/mnt/extData/Daten/" "/mnt/extMixedBackup1/extDataBackup/Daten" >> "$HOME/Documents/Zu_Sichern/Log_Backup_ExtData-to-ExtMixedBackup1/Log_Backup_ExtData-to-ExtMixedBackup1-`date +%Y-%m-%d-%X`" 2>&1'

#Handy related
alias handyBackupWA='adb pull /storage/self/primary/WhatsApp/Media/Whatsapp\ Images/'
alias handyBackupCam='adb pull /storage/self/primary/DCIM/Camera/'
alias handyBackupScreens='adb pull /storage/self/primary/Pictures/'
alias handyBackupThreemaPics='adb pull /storage/self/primary/Threema Pictures/'

#git related
alias gacp='git add * && git commit -m "Add Stuff" && git push'
